### PR TITLE
Rough draft of landing page and about page

### PR DESCRIPTION
**Pull request by Tsujibiha**
It should be close

### CODE REVIEW

**Comment by afuhrtrumpet** [comment]
You need to have the images added to the repo. Also, I'm going to try to add this in with index.html so it works with the scroll effect the other pages have.

**Comment by J3RN** [comment]
Is this one moving? Can I help out with this?

**Comment by afuhrtrumpet** [comment]
It's a rather complicated merge. I'm working on it.

**Comment by afuhrtrumpet** [comment]
The current version asks for "designcirclelogo.png" on the title page, which is not there. Is this supposed to be img/dc.png?

**Comment by afuhrtrumpet** [comment]
@J3RN, I added the new stuff in as sections. Do you want to try to fix the design and locate the missing images?

**Comment by J3RN** [comment]
I messaged @Tsujibiha about this, hopefully he will get around to it tomorrow. If not, I will just try to throw some in.

**Pull request merged**
