### PR TITLE
Snap to page scrolling

### PR DESCRIPTION
**Pull request by J3RN**
This is _more or less_ finished. There is an issue of the pages not being
exactly 100% of the window.

To see how Scrollify expects the site to be layed out, look at the [Scrollify
site](http://projects.lukehaas.me/scrollify/#overview).

### CODE REVIEW

**Comment by J3RN** [comment]
Closes #8.

Attached is the issue mentioned above.
screen shot 2015-02-10 at 1 27 04 pm

**Comment by J3RN** [comment]
@afuhrtrumpet Check this one out and let me know.

**Comment by afuhrtrumpet** [comment]
I like it, but why does events have a scrollbox now?

**Comment by J3RN** [comment]
Not sure if it was what you meant, but the scroll bar didn't hit bottom because the Blog page didn't have the `section` class. I just enabled it - check it out.

**Comment by afuhrtrumpet** [comment]
This is what I mean:
scrollblog
scrollevents
It wasn't happening before if I remember correctly.

**Comment by mrogman** [comment]
That was me, i turned scroll on for text overflow so the description didn't overlap with the links below. Those scroll bars didn't show up in my browser. We can maybe use ellipsis or just limit the number of chars allowed instead because that looks terrible

**Comment by J3RN** [comment]
Oh boy. Yeah, let's take that out. Also, it's not related to this PR - so let's move it to an issue or something.

**Pull request merged**
